# Generated by Django 5.2.3 on 2025-07-01 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contactlist_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_company', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient_position', models.CharField(blank=True, max_length=255, null=True)),
                ('email_subject', models.CharField(max_length=255)),
                ('email_body', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('contact_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.contactlist')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'resume', 'contact_list', 'recipient_email')},
            },
        ),
    ]
