# Generated by Django 5.2.3 on 2025-07-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_generatedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedemail',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedemail',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedemail',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedemail',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
